a = 1

try:
    a + 1

except:
    raise NameError('Aconteceu um Erro')

else:
    print('tudo OK')
